### ISSUE TITLE
Wrong user id sent on remote connection

### ISSUE THREAD

**Issue by tarta83** [FirebirdSQL/NETProvider#1075]
When connecting to a remote firebird database, the session fails with _"Your username and password are not defined"_. Using flamerobin on same client works without issue. It seems that the Firebird client is using the _logged on username_ instead of the _user id_ set in the connection string. Wrong user id can be seen in wireshark output below.

### Code for connection string and connect:

```
FbConnectionStringBuilder csb = new FbConnectionStringBuilder();
            csb.DataSource = "192.168.3.25";
            csb.Port = 3050;
            csb.Database = @"E:\FB_Datenbank\<name of database>.FDB";
            csb.UserID = "DOCUBIT";
            csb.Password = "docubit";
            csb.Charset = "WIN1252";            
            csb.ServerType = FbServerType.Default;            

            using (var connection = new FbConnection(csb.ConnectionString))
            {

                Console.WriteLine(connection.ConnectionString);
                connection.Open();
```

### Stacktrace of error

```
   bei FirebirdSql.Data.FirebirdClient.FbConnectionInternal.Connect()
   bei FirebirdSql.Data.FirebirdClient.FbConnection.Open()
   bei AMSConnect.DataAccess.FirebirdConnector.Connect() in C:\Users\xxx\source\repos\AMSConnect\AMSConnect\DataAccess\FirebirdConnector.cs: Zeile35
   bei Program.<Main>$(String[] args) in C:\Users\xxx\source\repos\AMSConnect\AMSConnect\Program.cs: Zeile12
```

### Wireshark output on server side:

```
Frame 15: 562 bytes on wire (4496 bits), 562 bytes captured (4496 bits) on interface \Device\NPF_{22AE4D68-AF56-410D-9E69-F8294C7680BC}, id 0
Ethernet II, Src: WatchGua_<mac firewall> (<mac firewall>), Dst: VMware_<mac server vm> (<mac server vm>)
Internet Protocol Version 4, Src: <src ip client>, Dst: 192.168.3.25
Transmission Control Protocol, Src Port: 56562, Dst Port: 3050, Seq: 1, Ack: 1, Len: 508
Firebird SQL Database Remote Protocol
    Opcode: Connect (1)
    Operation: Attach (19)
    Version: 3
    Client Architecture: Generic (1)
    Filename: E:\FB_Datenbank\<name of database>.FDB
    Version option count: 6
    **User ID: \001\b<windows-logon-user>\004\016<name of client pc>\006**
    Preferred version
    Preferred version
    Preferred version
    Preferred version
    Preferred version
    Preferred version
```

**Comment by mrotteveel** [comment]
The userid (`CNCT_user`) in that part of the connection handshake is not used for authentication. Your problem is more likely one of having a user created with the Legacy_Auth plugin, while the authentication (against Firebird 3.0 and higher) by the provider is only done with Srp and (possibly) Win_Sspi. Make sure you have a user created with Srp:

You can verify the user manager of a user by selecting from [`SEC$USERS`](https://www.firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref40/fblangref40-appx06-users.html).

```sql
create user <your-username> password '<your-password>' using plugin srp;
```

If this returns an error, check your Firebird config to ensure `Srp` is listed in the `UserManager` setting of `firebird.conf` (or `databases.conf` for that specific database).

If you still cannot authenticate, make sure the `Srp` and/or `Srp256` is listed in the `AuthServer` setting of `firebird.conf` (or `databases.conf` for that specific database).

BTW: this sounds more like a support question instead of a bug-report. Consider posting on https://groups.google.com/g/firebird-net-provider instead

**Comment by tarta83** [comment]
I wasn't aware of the user group and will follow your hints now. I will close this issue for now. Thanks!
