### ISSUE TITLE
Implement DDEX Provider as VSIX [DNET659]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#616]
Submitted by: André Ziegler (andre.ziegler)

Replaces [DNET581](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET581+in%3Atitle)
Replaces [DNET739](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET739+in%3Atitle)
Block progress on [DNET373](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET373+in%3Atitle)
Replaces [DNET623](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET623+in%3Atitle)

Votes: 1

To fix the issue, that the DDEX provider gets lost after updating an Visual Studio extension \([DNET581](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET581+in%3Atitle)\), implement/install the DDEX provider as VSPackage

**Comment by MagicAndre1981** [comment]
ok, I see the issues are migrated to github.

based on the fork of Daniel Rail (which is now deleted) I was able to to compile the VSIX with some modifications.

![firebird_vsix](https://user-images.githubusercontent.com/8274816/116979165-ef1aa380-acc4-11eb-80d4-561b597b9cf6.png)

I installed it a few weeks ago, compared to old installer, after updating other extensions it still works.

Some modifications are hardcoded paths to VS locations (which differ for each SKU) because some DLLs are not available as nugets.

Now I have no idea how to put his change history + my local modifications into a new pull request

**Comment by cincuranet** [comment]
I do not plan to keep DDEX, as discussed in the mailing list. Probably dropping it together with other changes related to .NET 6 (again, outlined in the list).

**Comment by cincuranet** [comment]
Closing because #1001.

**Comment by MagicAndre1981** [comment]
There is a now 3rd party DDEX provider and SQL editor available which works fine so far, so yes you can close it:

**BlackbirdSql DDEX and SqlEditor for Firebird**
https://marketplace.visualstudio.com/items?itemName=BlackbirdSql.BlackbirdSqlVisualStudioDdex

![Image](https://github.com/user-attachments/assets/ec54f510-2565-4283-be30-eb1826344a07)
