### ISSUE TITLE
Support for batch operations [DNET958]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#878]
Submitted by: @cincuranet

Is duplicated by [DNET858](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET858+in%3Atitle)
Jira\_subtask\_inward [DNET812](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET812+in%3Atitle)
Is duplicated by [DNET971](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET971+in%3Atitle)

**Comment by masonwheeler** [comment]
So... this issue has been open for almost a year with no discussion or indications of progress; just a bunch of posts from a bot indicating it's been imported from... where exactly?  If it's labeled as a major priority, it seems odd that no one is talking about it.

**Comment by cincuranet** [comment]
It has been imported from original JIRA tracker, which most people remember in a good or bad way.

About the discussion… I don't know. Maybe because people not yet migrated to freshly released FB4? Maybe it's not what people are interested compared to other features? Maybe something else. Just guessing.

The good news is, that I'm more than happy to take a contribution for this, so you can start working on it.

**Comment by cincuranet** [comment]
Done in c18fd52ad0e77ad07e38cddcb35c2116213b7268.

**Comment by cincuranet** [comment]
Although the low-level implementation is basically done, I'm still looking for feedback on developer facing API. You can discuss [here](https://groups.google.com/g/firebird-net-provider/c/7RjnQgfMg0M).

**Comment by houseofcat** [comment]
@cincuranet Very much looking forward DataReader support that supports the streaming/sequential access implementation.
