### ISSUE TITLE
Performance regression between 7.10.1 and 8.0.1 [DNET1042]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/NETProvider#953]
Submitted by: Rand Random (rand.random)

The performance to read data dropped to half between 7\.10\.1 and 8\.0\.1\.
On 7\.10\.1 my test finishes with 11\.14 s\.
On 8\.0\.1 my test finishes with 28\.72 s\.

I have created this github project with the code demonstrating my issue
<https://github.com/Rand-Random/FbPerf>

Only this file contains code:
<https://github.com/Rand-Random/FbPerf/blob/main/FbPerf8/FbPerfTest.cs>

This \*\.cs file reads 1 million rows from a database containing 5 million records\.
You can find the used database 7\-zipped as TESTPERF\.7z in the root of the github project, the file FbPerfTest\.cs also contains code how I created/filled the test database, in case it is relevent\.

The C#&#x2060; project FbPerf7 has the NuGet package for 7\.10\.1, while the C#&#x2060; project FbPerf8 has the NuGet package version 8\.0\.1\.
I am using BenchmarkDotNet for the performance tests, I added the results as images into the root of the github project\.
The perf7\.jpg contains the result for the FbPerf7 C#&#x2060; project, and the perf8\.jpg for the FbPerf8 C#&#x2060; project\.

Please be aware of the fact that the folder FbPerf7 only contains the \*\.csproj file and not a single \*\.cs file, this is because I am linking existing files from the FbPerf8 folder, I do this to avoid writing the test twice\.

**Comment by Rand-Random** [comment]
So that is why I can't reach the jira tracker anymore, everything got moved to github.
Did I miss an announcment? Are you also planning to move google groups to github discussions?

**Comment by cincuranet** [comment]
I did a quick look today. As expected the state machines generated are not helping. I need to dig into it and try to lower the impact (without implementing (and maintaining) everything twice).

Other thing to consider is whether the communication is over localhost or "real" network. Because with real network there's real asynchronicity.

Over Internet, with 20k fetches:
| Version | Time |
| --- | --- |
| 7.10.1 | 25.62 s |
| 8.0.1 | 25.21 s |

Obviously that doesn't mean the localhost performance is not important. Quite the contrary.

cc @Rand-Random
